repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-merge-conflict
    - id: mixed-branch-ending
      args: [--fix=crlf]
    - id: no-commit-to-branch
      args: [--branch, master, --branch, develop]

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      exclude: migrations
      args: [--profile, black, --line-length=78]

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
      args: [--line-length=78]

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      exclude: (migrations)
      additional_dependencies:
        - flake8-docstrings
