version: '3.3'

volumes:
  postgres_data_local:

services:
  lomaya_baryery_db-local:
    image: postgres:13.2
    restart: always
    container_name: lomaya_baryery_db-local
    volumes:
      - postgres_data_local:/var/lib/postgresql/data/
    ports:
      - "6100:6100"
    env_file:
      - ./.env
    command: -p 6100