version: '3.3'

volumes:
  postgres_data_stage:


services:
  postgres:
    image: postgres:13.2
    restart: always
    container_name: postgres_stage
    volumes:
      - postgres_data_stage:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

  backend:
    env_file:
      - .env
    container_name: lomaya_baryery_backend
    image: ghcr.io/studio-yandex-practicum/lomaya_baryery_backend:latest
    restart: always
    depends_on:
      - postgres

  nginx:
    image: nginx:1.23.2-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/static/:/var/html/static/
    depends_on:
      - backend
    env_file:
      - .env
