version: '3.3'

volumes:
  postgres_data_stage:
  static_value:
  nginx_config:


services:
  postgres:
    image: postgres:13.2
    restart: always
    container_name: postgres_stage
    volumes:
      - postgres_data_stage:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

  backend:
    env_file:
      - .env
    container_name: lomaya_baryery_backend
    image: ghcr.io/studio-yandex-practicum/lomaya_baryery_backend:latest
    restart: always
    depends_on:
      - postgres
    volumes:
      - static_value:/LOMAYA_BARYERY_BACKEND/src/static/
      - nginx_config:/LOMAYA_BARYERY_BACKEND/src/nginx/

  nginx:
    image: nginx:1.23.2-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - nginx_config:/etc/nginx/conf.d/
    depends_on:
      - backend
    env_file:
      - .env
