version: '3.3'

volumes:
  postgres_data_stage:
  static_value:
  nginx_config:


services:
  postgres:
    image: postgres:13.2
    container_name: postgres_stage
    restart: always
    volumes:
      - postgres_data_stage:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

  backend:
    image: ghcr.io/studio-yandex-practicum/lomaya_baryery_backend:latest
    container_name: lomaya_baryery_backend
    restart: always
    depends_on:
      - postgres
    volumes:
      - static_value:/LOMAYA_BARYERY_BACKEND/src/static/
    env_file:
      - .env

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - URL=mspiridonov.tk
      - VALIDATION=http
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
    volumes:
      - static_value:/config/static/
      - ./src/nginx/default.conf:/etc/nginx/conf.d/lombaryery.subfolder.conf
    env_file:
      - .env
