version: '3.3'

volumes:
  postgres_data:

services:
  db:
    image: postgres:13.2
    container_name: lomaya_baryery_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    build: .
    container_name: lomaya_baryery_backend
    ports:
      - "8080:8080"
    restart: always
    command: python run.py
    depends_on:
      - db
    env_file:
      - ./.env
