name: Check Migrations

on:
  pull_request:
    branches:
      - develop
      - master

env:
  DB_PORT: 5432

jobs:
  migrations:
    name: Check Migrations
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: lomaya_baryery_db_local
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build image
        uses: ./.github/actions/build

      - name: Alembic Upgrade
        run: poetry run alembic upgrade head

      - name: Check Migrations
        run: poetry run alembic-autogen-check --config ./alembic.ini

      - name: Make testing
        run: poetry run pytest
