name: codestyle

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  codestyle:
    name: Check codestyle
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: 'codestyle-requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r codestyle-requirements.txt

      - name: Lint with flake8
        run: python -m flake8

      - name: Codestyle by black
        run: black --check --config=pyproject.toml .
