name: Check codestyle

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  codestyle:
    name: Check codestyle
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Load cached poetry installation
        id: cached-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-v1-${{ hashFiles('pyproject.toml') }}

      - name: Install poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2

      - name: Install python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'poetry'

      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: |
          poetry install --only=lint

      - name: Lint with flake8
        run: poetry run flake8 --config setup.cfg

      - name: Codestyle by black
        run: poetry run black --check --config=pyproject.toml .
