name: Check codestyle

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  codestyle:
    name: Check codestyle
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build image
        uses: ./.github/actions/build

      - name: Lint with flake8
        run: poetry run flake8 --config setup.cfg

      - name: Codestyle by black
        run: poetry run black --check --config=pyproject.toml .
