name: every push health check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - master


env:
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: lomaya_baryery_db_local
  POSTGRES_USER: postgres
  DB_HOST: localhost
  DB_PORT: 5432

jobs:
  healthcheck:
    name: Check workable app
    runs-on: ubuntu-latest
    environment:
      name: healthcheck
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: lomaya_baryery_db_local
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    -
      name: Check out the repo
      uses: actions/checkout@v3
    -
      name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    -
      name: Install and configure Poetry
      uses: snok/install-poetry@v1
    -
      name: Install Dependencies
      run: |
        python -V
        poetry config virtualenvs.in-project true
        poetry install
    -
      name: Create .env file
      run: |
        touch .env
        echo BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} >> .env
        echo APPLICATION_URL=localhost >> .env
        echo HEALTHCHECK_API_URL='http://localhost:8080/docs' >> .env

    -
      name: Alembic Upgrade
      run: poetry run alembic upgrade head
    -
      name: Run Local project
      run: timeout 120 poetry run python run.py &
    -
      name: Get the status of healthcheck
      uses: im-open/url-status-check@v1.1.0
      with:
        url: 'http://localhost:8080/healthcheck'
        fail-on-bad-status: true
