name: every push health check

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  healthcheck:
    name: Check workable app
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: lomaya_baryery_db_local
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    -
      name: Check out the repo
      uses: actions/checkout@v2
    -
      name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - 
      name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    -
      name: Install Dependencies
      run: |
        poetry install
        poetry shell
    - 
      name: Create env file
      run: mv .env.example .env
    -
      name: Alembic Upgrade
      run: poetry alembic upgrade heads
    -
      name: Run Local project
      run: python run.py
    - 
      name: Get the status of healthcheck
      uses: im-open/url-status-check@v1.1.0
      with:
        url: 'http://localhost:8080/healthcheck'
        fail-on-bad-status: true
      