name: test yaml

on:
  push:
    branches:
      - feature/ci_cd

jobs:
  test:
    name: Test yaml
    runs-on: ubuntu-latest
    environment:
      name: Stage
    steps:

      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo rm -f .env
            touch .env
